export const PRESETS = [
  {
    name: "V4 Flash - Basic Chat",
    description: "Simple non-thinking chat with deepseek-v4-flash",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-flash",
      messages: [
        { role: "system", content: "You are a helpful assistant." },
        { role: "user", content: "Hello! How are you?" },
      ],
      maxTokens: 1024,
      temperature: 1.0,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "V4 Pro - Thinking Mode",
    description: "Deep thinking with deepseek-v4-pro, effort=high",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-pro",
      messages: [
        { role: "system", content: "You are a helpful assistant." },
        { role: "user", content: "9.11 and 9.8, which is greater? Explain your reasoning step by step." },
      ],
      maxTokens: 4096,
      temperature: 1.0,
      topP: 1.0,
      stream: false,
      thinking: { type: "enabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "V4 Pro - Max Reasoning",
    description: "Maximum reasoning effort with deepseek-v4-pro",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-pro",
      messages: [
        { role: "system", content: "You are a helpful assistant." },
        { role: "user", content: "Prove that the square root of 2 is irrational." },
      ],
      maxTokens: 8192,
      temperature: 1.0,
      topP: 1.0,
      stream: false,
      thinking: { type: "enabled" },
      reasoningEffort: "max",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "JSON Output",
    description: "Structured JSON response with explicit schema instruction",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-flash",
      messages: [
        { role: "system", content: 'You are a data extraction assistant. Output valid JSON only. Example: {"name": "...", "age": 25}' },
        { role: "user", content: "Extract info: John Doe is 30 years old and lives in New York." },
      ],
      maxTokens: 1024,
      temperature: 0.3,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "json_object" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "Tool Calls Demo",
    description: "Function calling with weather tool",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-pro",
      messages: [
        { role: "user", content: "What's the weather like in Hangzhou?" },
      ],
      maxTokens: 2048,
      temperature: 0.7,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [
        {
          type: "function",
          function: {
            name: "get_weather",
            description: "Get weather of a location, the user should supply a location first.",
            parameters: {
              type: "object",
              properties: {
                location: { type: "string", description: "City name" },
              },
              required: ["location"],
            },
          },
        },
      ],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "Thinking + Tool Calls",
    description: "V4 Pro thinking mode with tool usage",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-pro",
      messages: [
        { role: "user", content: "How's the weather in Hangzhou tomorrow?" },
      ],
      maxTokens: 4096,
      temperature: 1.0,
      topP: 1.0,
      stream: false,
      thinking: { type: "enabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [
        {
          type: "function",
          function: {
            name: "get_date",
            description: "Get the current date",
            parameters: { type: "object", properties: {} },
          },
        },
        {
          type: "function",
          function: {
            name: "get_weather",
            description: "Get weather of a location",
            parameters: {
              type: "object",
              properties: {
                location: { type: "string", description: "City name" },
                date: { type: "string", description: "Date in YYYY-mm-dd" },
              },
              required: ["location", "date"],
            },
          },
        },
      ],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "Stream + Token Usage",
    description: "Streaming response with usage data",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-flash",
      messages: [
        { role: "system", content: "You are a helpful assistant." },
        { role: "user", content: "Write a short poem about artificial intelligence." },
      ],
      maxTokens: 2048,
      temperature: 0.8,
      topP: 1.0,
      stream: true,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: true },
    },
  },
  {
    name: "FIM Code Completion",
    description: "Fill-in-the-Middle code completion (Beta)",
    request: {
      endpoint: "completions",
      model: "deepseek-v4-pro",
      prompt: "def fibonacci(n):\n    ",
      suffix: "\n    return fib(n)",
      maxTokens: 256,
      temperature: 0.3,
      topP: 1.0,
      stream: false,
      stop: ["\n\n"],
      logprobs: 0,
      echo: false,
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "Prefix Completion",
    description: "Force model to continue from a prefix (Beta)",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-pro",
      messages: [
        { role: "user", content: "Write a Python function to sort a list." },
        { role: "assistant", content: "```python\n", prefix: true },
      ],
      maxTokens: 512,
      temperature: 0.3,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: ["```"],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "Logprobs Analysis",
    description: "Examine token log probabilities",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-flash",
      messages: [
        { role: "user", content: "What is the capital of France?" },
      ],
      maxTokens: 64,
      temperature: 0.0,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: true,
      topLogprobs: 5,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "Multi-Round Conversation",
    description: "Two turns: model remembers context",
    request: {
      endpoint: "chat/completions",
      model: "deepseek-v4-flash",
      messages: [
        { role: "user", content: "What's the highest mountain in the world?" },
        { role: "assistant", content: "Mount Everest" },
        { role: "user", content: "What is the second highest?" },
      ],
      maxTokens: 1024,
      temperature: 0.7,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "List Models",
    description: "Fetch available DeepSeek models",
    request: {
      endpoint: "models",
      model: "",
      messages: [],
      maxTokens: 0,
      temperature: 1.0,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
  {
    name: "Get Balance",
    description: "Check your DeepSeek API account balance",
    request: {
      endpoint: "user/balance",
      model: "",
      messages: [],
      maxTokens: 0,
      temperature: 1.0,
      topP: 1.0,
      stream: false,
      thinking: { type: "disabled" },
      reasoningEffort: "high",
      stop: [],
      responseFormat: { type: "text" },
      logprobs: false,
      topLogprobs: 0,
      userId: "",
      tools: [],
      toolChoice: "auto",
      streamOptions: { includeUsage: false },
    },
  },
];

export function getDefaultRequest() {
  return JSON.parse(JSON.stringify(PRESETS[0].request));
}
