/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as ApiDsCompleteRouteImport } from './routes/api/ds/complete'
import { Route as ApiDsLoginRouteImport } from './routes/api/ds/login'
import { Route as ApiDsMeRouteImport } from './routes/api/ds/me'
import { Route as ApiDsSessionRouteImport } from './routes/api/ds/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDsCompleteRoute = ApiDsCompleteRouteImport.update({
  id: '/api/ds/complete',
  path: '/api/ds/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDsLoginRoute = ApiDsLoginRouteImport.update({
  id: '/api/ds/login',
  path: '/api/ds/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDsMeRoute = ApiDsMeRouteImport.update({
  id: '/api/ds/me',
  path: '/api/ds/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDsSessionRoute = ApiDsSessionRouteImport.update({
  id: '/api/ds/session',
  path: '/api/ds/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/import': typeof ApiImportRoute
  '/api/ds/complete': typeof ApiDsCompleteRoute
  '/api/ds/login': typeof ApiDsLoginRoute
  '/api/ds/me': typeof ApiDsMeRoute
  '/api/ds/session': typeof ApiDsSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/import': typeof ApiImportRoute
  '/api/ds/complete': typeof ApiDsCompleteRoute
  '/api/ds/login': typeof ApiDsLoginRoute
  '/api/ds/me': typeof ApiDsMeRoute
  '/api/ds/session': typeof ApiDsSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/import': typeof ApiImportRoute
  '/api/ds/complete': typeof ApiDsCompleteRoute
  '/api/ds/login': typeof ApiDsLoginRoute
  '/api/ds/me': typeof ApiDsMeRoute
  '/api/ds/session': typeof ApiDsSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/import'
    | '/api/ds/complete'
    | '/api/ds/login'
    | '/api/ds/me'
    | '/api/ds/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/import'
    | '/api/ds/complete'
    | '/api/ds/login'
    | '/api/ds/me'
    | '/api/ds/session'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/import'
    | '/api/ds/complete'
    | '/api/ds/login'
    | '/api/ds/me'
    | '/api/ds/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImportRoute: typeof ApiImportRoute
  ApiDsCompleteRoute: typeof ApiDsCompleteRoute
  ApiDsLoginRoute: typeof ApiDsLoginRoute
  ApiDsMeRoute: typeof ApiDsMeRoute
  ApiDsSessionRoute: typeof ApiDsSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ds/complete': {
      id: '/api/ds/complete'
      path: '/api/ds/complete'
      fullPath: '/api/ds/complete'
      preLoaderRoute: typeof ApiDsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ds/login': {
      id: '/api/ds/login'
      path: '/api/ds/login'
      fullPath: '/api/ds/login'
      preLoaderRoute: typeof ApiDsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ds/me': {
      id: '/api/ds/me'
      path: '/api/ds/me'
      fullPath: '/api/ds/me'
      preLoaderRoute: typeof ApiDsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ds/session': {
      id: '/api/ds/session'
      path: '/api/ds/session'
      fullPath: '/api/ds/session'
      preLoaderRoute: typeof ApiDsSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImportRoute: ApiImportRoute,
  ApiDsCompleteRoute: ApiDsCompleteRoute,
  ApiDsLoginRoute: ApiDsLoginRoute,
  ApiDsMeRoute: ApiDsMeRoute,
  ApiDsSessionRoute: ApiDsSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
